"""AI response parsing module for ThreatPilot.

Contains the logic to extract structured JSON data from raw AI responses,
handling various formatting artifacts such as markdown code blocks.
"""

from __future__ import annotations

import json
import re
from typing import Any, Dict, List, Optional


def extract_json(text: str) -> Optional[Any]:
    """Helper to extract a JSON object from a text string.

    Handles markdown code blocks and attempts to auto-repair truncated 
    JSON by backtracking to the last valid object in a list.

    Args:
        text: The raw response text from the AI.

    Returns:
        The parsed Python object (list or dict), or ``None`` if no JSON
        could be extracted/parsed.
    """
    if not text:
        return None

    # 1. Primary Extraction: Try to find a JSON block via markdown or raw markers
    content = ""
    # Look for markdown block
    code_block_match = re.search(r"```(?:json)?\s*([\s\S]*?)(?:```|$)", text)
    if code_block_match:
        content = code_block_match.group(1).strip()
    else:
        # Fallback: Find matching start marker
        first_brace = text.find("{")
        first_bracket = text.find("[")
        start_idx = -1
        if first_brace != -1 and (first_bracket == -1 or first_brace < first_bracket):
            start_idx = first_brace
        elif first_bracket != -1:
            start_idx = first_bracket
            
        if start_idx == -1:
            return None
        content = text[start_idx:].strip()

    if not content:
        return None

    # 2. Iterative Recovery: If JSON is truncated, backtrack to find the last valid segment
    # This is much more robust than just adding closing brackets to a broken string.
    
    # Simple direct attempt first
    try:
        # Pre-clean: common trailing comma issue
        clean_content = re.sub(r",\s*([\]\}])", r"\1", content)
        return json.loads(clean_content)
    except json.JSONDecodeError:
        pass

    # Recovery Strategy for Lists: find the last complete object '}'
    if content.startswith("["):
        # Iterate backwards from the last '}' found
        last_brace = content.rfind("}")
        while last_brace != -1:
            candidate = content[:last_brace + 1].strip()
            # If there's a trailing comma after the last brace, remove it
            if candidate.endswith(","):
                candidate = candidate[:-1].strip()
            
            # Close the list
            candidate += "]"
            
            try:
                # Clean up nested commas if any
                candidate = re.sub(r",\s*([\]\}])", r"\1", candidate)
                return json.loads(candidate)
            except json.JSONDecodeError:
                # Backtrack further
                last_brace = content.rfind("}", 0, last_brace)
        
    # Recovery Strategy for Single Objects
    elif content.startswith("{"):
        last_brace = content.rfind("}")
        if last_brace != -1:
            candidate = content[:last_brace + 1]
            try:
                candidate = re.sub(r",\s*([\]\}])", r"\1", candidate)
                return json.loads(candidate)
            except json.JSONDecodeError:
                pass
                
    return None


def parse_threat_list(raw_response: str) -> List[Dict[str, Any]]:
    """Parse a list of threats from the AI's response text.

    Expected format (from PromptBuilder):
        A list of JSON objects with:
        threat_id, category, title, description, impact, likelihood, recommended_mitigation

    Args:
        raw_response: The text generated by the AI provider.

    Returns:
        A list of extracted dictionaries containing threat metadata.
    """
    obj = extract_json(raw_response)
    if isinstance(obj, list):
        return obj
    if isinstance(obj, dict):
        # Handle cases where AI wraps the list in a key like 'threats'
        for key in ("threats", "analysis", "results"):
            if key in obj and isinstance(obj[key], list):
                return obj[key]
        return [obj]
    
    return []
