"""Core domain models for architectural components, data flows, and trust boundaries."""

from __future__ import annotations
import uuid
from enum import Enum
from typing import Any, Optional
from pydantic import BaseModel, Field

class ElementType(str, Enum):
    """Standard Data Flow Diagram (DFD) element types."""
    PROCESS = "Process"
    DATA_STORE = "Data Store"
    DATA_FLOW = "Data Flow"
    ENTITY = "Entity"
    NONE = "None"

class AssetType(str, Enum):
    """Classification for physical and informational assets."""
    PHYSICAL = "Physical"
    INFORMATIONAL = "Informational"
    NONE = "None"

class Asset(BaseModel):
    """A high-value asset residing within the system architecture."""
    asset_id: str = Field(default_factory=lambda: uuid.uuid4().hex)
    name: str = "New Asset"
    type: AssetType = AssetType.INFORMATIONAL
    description: str = ""
    criticality: str = "Medium"
    is_out_of_scope: bool = False
    out_of_scope_justification: str = ""

class Component(BaseModel):
    """A logical or physical system component (DFD Node)."""
    component_id: str = Field(default_factory=lambda: uuid.uuid4().hex)
    name: str = "New Component"
    type: str = "Service"
    element_type: ElementType = ElementType.PROCESS
    asset_type: AssetType = AssetType.INFORMATIONAL
    trust_boundary_id: Optional[str] = None
    description: str = ""
    is_out_of_scope: bool = False
    out_of_scope_justification: str = ""
    x: float = 0.0
    y: float = 0.0
    width: float = 100.0
    height: float = 100.0

class Flow(BaseModel):
    """A data flow representing communication between two components."""
    flow_id: str = Field(default_factory=lambda: uuid.uuid4().hex)
    name: str = "Data Flow"
    source_id: str = ""
    target_id: str = ""
    protocol: str = "HTTPS"
    description: str = ""
    is_out_of_scope: bool = False
    out_of_scope_justification: str = ""
    is_bidirectional: bool = False
    trust_boundary_id: Optional[str] = None
    start_x: float = 0.0
    start_y: float = 0.0
    end_x: float = 0.0
    end_y: float = 0.0
    authentication: str = ""
    encryption: str = ""
    assets: list[str] = Field(default_factory=list)

class TrustBoundary(BaseModel):
    """A boundary group encompassing multiple components and flows."""
    boundary_id: str = Field(default_factory=lambda: uuid.uuid4().hex)
    name: str = "Trust Boundary"
    type: str = "Internal"
    description: str = ""
    parent_boundary_id: Optional[str] = None
    x: float = 0.0
    y: float = 0.0
    width: float = 200.0
    height: float = 200.0

class MitigationRequirement(BaseModel):
    """A consolidated mitigation requirement generated by AI."""
    req_id: str = ""
    title: str = ""
    affected_components: str = ""
    mitigation: str = ""
    short_description: str = ""
    test_case: str = ""
    reasoning: str = ""