"""Markdown report exporter module for ThreatPilot.

Generates a structured, human-readable security analysis report in Markdown
format based on the current project metadata and threat register.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from threatpilot.core.project_manager import Project


def export_to_markdown(project: Project, output_path: str | Path) -> None:
    """Generate a comprehensive Markdown threat model report.

    Includes project metadata, industry context, STRIDE analysis methodology,
    and a detailed registry of identified threats.

    Args:
        project: The complete Project instance.
        output_path: Path where the .md file will be saved.

    Raises:
        OSError: If the file cannot be written to disk.
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    lines = [
        f"# ThreatPilot Security Analysis Report: {project.project_name}",
        f"*Generated on: {now}*",
        "",
        "## 1. Project Overview",
        f"- **Project Name:** {project.project_name}",
        f"- **Created:** {project.created_at}",
        f"- **Industry Context:** {project.prompt_config.industry_context or 'General'}",
        f"- **Security Posture:** {project.prompt_config.security_posture}",
        f"- **Risk Preference:** {project.prompt_config.risk_preference}",
        "",
        "## 2. Threat Analysis Methodology",
        "The system was analyzed using the **STRIDE** methodology. "
        "Threats were identified and categorized as Spoofing, Tampering, "
        "Repudiation, Information Disclosure, Denial of Service, or Elevation of Privilege.",
        "",
        "## 3. Risk Register Summary",
    ]

    # Summarise counts
    threats = project.threat_register.threats
    if not threats:
        lines.append("_No threats identified in the current register._")
    else:
        accepted_count = sum(1 for t in threats if t.is_accepted_risk)
        lines.append(f"- **Total Identified Threats:** {len(threats)}")
        lines.append(f"- **Accepted Risks:** {accepted_count}")
        lines.append(f"- **Pending Mitigations:** {len(threats) - accepted_count}")
        
        lines.append("")
        lines.append("## 4. Detailed Findings")
        
        # Group by category for cleaner output
        from collections import defaultdict
        grouped = defaultdict(list)
        for t in threats:
            grouped[t.category.value].append(t)
            
        for category, items in grouped.items():
            lines.append(f"### {category}")
            for t in items:
                status = "✅ [ACCEPTED]" if t.is_accepted_risk else "❌ [ACTIVE]"
                
                # Derive severity from CVSS score
                from threatpilot.risk.cvss_calculator import get_cvss_severity
                severity = get_cvss_severity(t.cvss_score)
                
                # Extract component-level classifications
                comp_details = []
                if t.affected_components:
                    names = [n.strip() for n in t.affected_components.split(",")]
                    for name in names:
                        for c in project.components:
                            if c.name == name:
                                comp_details.append(f"{c.name} ({c.element_classification} / {c.asset_classification})")
                                break
                
                lines.append(f"#### {status} {t.title}")
                lines.append(f"- **Risk Level:** {severity} (Score: {t.cvss_score})")
                lines.append(f"- **Likelihood:** {t.likelihood}/5")
                if t.cvss_vector:
                    lines.append(f"- **CVSS Vector:** `{t.cvss_vector}`")
                
                if comp_details:
                    lines.append(f"- **Affected Assets:** {', '.join(comp_details)}")
                elif t.affected_components:
                    lines.append(f"- **Affected Components:** {t.affected_components}")
                
                lines.append(f"- **Description:** {t.description}")
                if t.vulnerabilities:
                    lines.append(f"- **Vulnerabilities:** {t.vulnerabilities}")
                lines.append(f"- **Impact:** {t.impact}")
                lines.append(f"- **Mitigation Strategy:** {t.mitigation}")
                
                if t.is_accepted_risk and t.acceptance_justification:
                    lines.append(f"- **Acceptance Rationale:** {t.acceptance_justification}")
                lines.append("")

    lines.append("---")
    lines.append("*End of Report - Generated by ThreatPilot*")

    # Write to file
    Path(output_path).write_text("\n".join(lines), encoding="utf-8")
