from __future__ import annotations
import logging
from datetime import datetime
from pathlib import Path
from collections import defaultdict

from threatpilot.core.project_manager import Project
from threatpilot.risk.cvss_calculator import get_cvss_severity

logger = logging.getLogger(__name__)

def sanitize_md(text: str | None) -> str:
    """Escape Markdown special characters and collapse to single line."""
    if not text:
        return ""
    str_val = str(text).replace("\n", " ").replace("\r", " ").strip()
    escape_chars = r"\\`*_{}[]()#+-.!"
    for char in escape_chars:
        str_val = str_val.replace(char, f"\\{char}")
    return str_val

def export_mitigation_checklist(project: Project, output_path: str | Path) -> None:
    """Generates a Markdown checklist in the format: Element -> Threats -> Mitigations."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    lines = [
        f"# Mitigation Checklist: {sanitize_md(project.project_name)}",
        f"*Generated on: {now}*",
        "",
        "## Executive Summary",
        "This document provides a hierarchical checklist of threats, vulnerabilities, and mitigations "
        "grouped by architectural elements.",
        "",
    ]

    threats = project.threat_register.threats
    if not threats:
        lines.append("_No threats or mitigations identified yet._")
    else:
        # Group threats by affected element
        element_map = defaultdict(list)
        
        for t in threats:
            if t.is_accepted_risk:
                continue
                
            elem_name, _ = t.resolve_affected_elements(project)
            if not elem_name:
                elem_name = "Global / Unassigned"
            
            element_map[elem_name].append(t)

        if not element_map:
            lines.append("_All identified risks have been accepted. No pending mitigations._")
        else:
            # Sort elements alphabetically
            for elem in sorted(element_map.keys()):
                lines.append(f"### 🏗️ {sanitize_md(elem)}")
                
                # --- THREATS SECTION ---
                lines.append("- **Threats**")
                element_threats = sorted(element_map[elem], key=lambda x: x.cvss_score, reverse=True)
                
                # To collect unique mitigations for this element
                unique_mitigations = set()
                
                for t in element_threats:
                    severity = get_cvss_severity(t.cvss_score)
                    lines.append(f"  - [ ] **{sanitize_md(t.title)}** (Severity: {severity})")
                    
                    # Store mitigation for later
                    if t.mitigation:
                        unique_mitigations.add(t.mitigation.strip())
                    
                    # Include vulnerabilities
                    if t.vulnerability_ids and hasattr(project, "vulnerability_register"):
                        for vid in t.vulnerability_ids:
                            v = project.vulnerability_register.get_vulnerability(vid)
                            if v and v.description:
                                lines.append(f"    - {sanitize_md(v.description)}")
                
                # --- MITIGATIONS SECTION ---
                lines.append("- **Mitigations**")
                if not unique_mitigations:
                    lines.append("  - _No specific mitigations identified._")
                else:
                    # Sort mitigations for consistency
                    for mit in sorted(list(unique_mitigations)):
                        lines.append(f"  - [ ] {sanitize_md(mit)}")
                
                lines.append("")

    lines.append("---")
    lines.append("*Generated by ThreatPilot - Empowering Architectural Security*")
    
    try:
        Path(output_path).write_text("\n".join(lines), encoding="utf-8")
        logger.info(f"Mitigation checklist exported to {output_path}")
    except Exception as e:
        logger.error(f"Failed to export mitigation checklist: {e}")
        raise
